name: CI

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run type-check || npm run typecheck
        continue-on-error: true

      - name: Test frontend
        run: npm run test:frontend || npm run test

      - name: Test backend
        run: npm run test:backend || npm run test

      - name: Build client
        run: npm run build:client || npm run build

      # - name: Slack notification (optional)
      #   uses: 8398a7/action-slack@v3
      #   with:
      #     status: ${{ job.status }}
      #     fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 